### ISSUE TITLE
Can't install - 404 on pre-built binaries? No make file on source compile?

### ISSUE THREAD

**Issue by cstrat** [abandonware/node-bluetooth-hci-socket#29]
Unsure if this is just me but I can't install Noble because of this package.
Trying to install the package directly I get these same errors. 

I've got all the right libs installed from the noble FAQ for Ubuntu.
I've set the permissions correct too for root access.
I've installed `node-gyp` globally.

```
npm WARN deprecated node-pre-gyp@0.17.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future

> usb@1.7.2 install /home/server/home-server/microservices/temperatures/node_modules/usb
> prebuild-install --runtime napi --target 4 --verbose || node-gyp rebuild

prebuild-install info begin Prebuild-install version 5.3.6
prebuild-install info looking for cached prebuild @ /home/server/.npm/_prebuilds/8627f2-usb-v1.7.2-napi-v4-linux-x64.tar.gz
prebuild-install info found cached prebuild 
prebuild-install info unpacking @ /home/server/.npm/_prebuilds/8627f2-usb-v1.7.2-napi-v4-linux-x64.tar.gz
prebuild-install info unpack resolved to /home/server/home-server/microservices/temperatures/node_modules/usb/build/Release/usb_bindings.node
prebuild-install info install Successfully installed prebuilt binary!

> @abandonware/bluetooth-hci-socket@0.5.3-7 install /home/server/home-server/microservices/temperatures/node_modules/@abandonware/bluetooth-hci-socket
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using needle for node-pre-gyp https download 
node-pre-gyp WARN Tried to download(404): https://github.com/abandonware/node-bluetooth-hci-socket/releases/download/0.5.3-7/bluetooth_hci_socket-0.5.3-7-node-v83-linux-x64.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for @abandonware/bluetooth-hci-socket@0.5.3-7 and node@14.17.6 (node-v83 ABI, glibc) (falling back to source compile with node-gyp) 
gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/home/server/.nvm/versions/node/v14.17.6/lib/node_modules/npm/node_modules/which/which.js:13:12)
gyp ERR! stack     at F (/home/server/.nvm/versions/node/v14.17.6/lib/node_modules/npm/node_modules/which/which.js:68:19)
gyp ERR! stack     at E (/home/server/.nvm/versions/node/v14.17.6/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /home/server/.nvm/versions/node/v14.17.6/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /home/server/.nvm/versions/node/v14.17.6/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /home/server/.nvm/versions/node/v14.17.6/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:192:21)
gyp ERR! System Linux 5.4.0-81-generic
gyp ERR! command "/home/server/.nvm/versions/node/v14.17.6/bin/node" "/home/server/.nvm/versions/node/v14.17.6/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/server/home-server/microservices/temperatures/node_modules/@abandonware/bluetooth-hci-socket/lib/binding/bluetooth_hci_socket.node" "--module_name=bluetooth_hci_socket" "--module_path=/home/server/home-server/microservices/temperatures/node_modules/@abandonware/bluetooth-hci-socket/lib/binding" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v83"
gyp ERR! cwd /home/server/home-server/microservices/temperatures/node_modules/@abandonware/bluetooth-hci-socket
gyp ERR! node -v v14.17.6
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/home/server/.nvm/versions/node/v14.17.6/bin/node /home/server/.nvm/versions/node/v14.17.6/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/server/home-server/microservices/temperatures/node_modules/@abandonware/bluetooth-hci-socket/lib/binding/bluetooth_hci_socket.node --module_name=bluetooth_hci_socket --module_path=/home/server/home-server/microservices/temperatures/node_modules/@abandonware/bluetooth-hci-socket/lib/binding --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/server/home-server/microservices/temperatures/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1055:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
node-pre-gyp ERR! System Linux 5.4.0-81-generic
node-pre-gyp ERR! command "/home/server/.nvm/versions/node/v14.17.6/bin/node" "/home/server/home-server/microservices/temperatures/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/server/home-server/microservices/temperatures/node_modules/@abandonware/bluetooth-hci-socket
node-pre-gyp ERR! node -v v14.17.6
node-pre-gyp ERR! node-pre-gyp -v v0.17.0
node-pre-gyp ERR! not ok 
Failed to execute '/home/server/.nvm/versions/node/v14.17.6/bin/node /home/server/.nvm/versions/node/v14.17.6/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/server/home-server/microservices/temperatures/node_modules/@abandonware/bluetooth-hci-socket/lib/binding/bluetooth_hci_socket.node --module_name=bluetooth_hci_socket --module_path=/home/server/home-server/microservices/temperatures/node_modules/@abandonware/bluetooth-hci-socket/lib/binding --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
npm WARN microservices@1.0.0 No description
npm WARN microservices@1.0.0 No repository field.
```

**Comment by Apollon77** [comment]
> gyp ERR! stack Error: not found: make

Then you should install the usual build tools. try to "apt install build-essential"

**Comment by cstrat** [comment]
Oh thank you so much that was it. Not sure how I haven't run into this issue already with other packages...!
